version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0"
    volumes:
      - ./app:/app/app
      - ./instance:/app/instance
      - ./celery_worker.py:/app/celery_worker.py
      - ./migrations:/app/migrations
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - ./app:/app/app
      - ./instance:/app/instance
      - ./celery_worker.py:/app/celery_worker.py
      - ./migrations:/app/migrations
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: celery -A celery_worker.celery beat --loglevel=info
    volumes:
      - ./app:/app/app
      - ./instance:/app/instance
      - ./celery_worker.py:/app/celery_worker.py
    env_file:
      - .env
    depends_on:
      - celery_worker
      - redis

  flower:
    build: .
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app/app
      - ./instance:/app/instance
      - ./celery_worker.py:/app/celery_worker.py
    env_file:
      - .env
    depends_on:
      - celery_worker
      - redis

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=ticket_booking
  #   ports:
  #     - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data: 